//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sc2test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sc2test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _129552993571305435 {
            get {
                object obj = ResourceManager.GetObject("_129552993571305435", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] _2v2_alodia_daddynick_hydrokat_ifry {
            get {
                object obj = ResourceManager.GetObject("_2v2_alodia_daddynick_hydrokat_ifry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bad {
            get {
                object obj = ResourceManager.GetObject("bad", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meta_1 {
            get {
                object obj = ResourceManager.GetObject("meta_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meta_2 {
            get {
                object obj = ResourceManager.GetObject("meta_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meta_3 {
            get {
                object obj = ResourceManager.GetObject("meta_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meta_4 {
            get {
                object obj = ResourceManager.GetObject("meta_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] other_1 {
            get {
                object obj = ResourceManager.GetObject("other_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] other_2 {
            get {
                object obj = ResourceManager.GetObject("other_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] other_3 {
            get {
                object obj = ResourceManager.GetObject("other_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
